pipeline {
    agent any
    parameters {
        string(defaultValue : "TEST",description: "Which environment?", name: "deployEnv")
    }
    stages{
        stage ("param demo"){
            steps {
                echo "Deployment env is set to : ${params.deployEnv}"
            }
        }
    }
}